/*
 * pact-example
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PactExample);
  }
}(this, function(expect, PactExample) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PactExample.TodosApi();
  });

  describe('(package)', function() {
    describe('TodosApi', function() {
      describe('todosTodoIdGet', function() {
        it('should call todosTodoIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for todosTodoIdGet call and complete the assertions
          /*
          var todoId = 789;

          instance.todosTodoIdGet(todoId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PactExample.Todos);
            expect(data.userId).to.be.a('number');
            expect(data.userId).to.be(1);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be(1);
            expect(data.title).to.be.a('string');
            expect(data.title).to.be("delectus aut autem");
            expect(data.completed).to.be.a('boolean');
            expect(data.completed).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
